name: Deploy Nuxt SSR

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to HOMELAB
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22

          script: |
            set -e

            echo "======================================"
            echo " Deploy Galery Mahendra"
            echo "======================================"

            PROJECT="/www/wwwroot/galery-mahendra"
            APP_PATH="/www/server/nodejs/v22.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

            echo "=== Update source from GitHub ==="

            sudo -u www -H env PATH="$APP_PATH" bash -c "
              cd '$PROJECT'

              echo 'Git version:'
              git --version

              git config --global --add safe.directory '$PROJECT'

              git fetch origin main
              git reset --hard origin/main
            "

            echo "=== Install dependencies ==="

            sudo -u www -H env PATH="$APP_PATH" bash -c "
              cd '$PROJECT'

              echo 'Node version:'
              node -v

              echo 'NPM version:'
              npm -v

              npm ci
            "

            echo "=== Build Nuxt SSR ==="

            sudo -u www -H env PATH="$APP_PATH" bash -c "
              cd '$PROJECT'
              npm run build
            "

            echo "=== Restart PM2 ==="

            sudo -u www -H env PATH="$APP_PATH" \
              pm2 restart galery_mahendra --update-env

            echo "=== Save PM2 ==="

            sudo -u www -H env PATH="$APP_PATH" \
              pm2 save

            echo "=== PM2 Status ==="

            sudo -u www -H env PATH="$APP_PATH" \
              pm2 status galery_mahendra

            echo "======================================"
            echo " DEPLOY SUCCESS"
            echo "======================================"
